### PR TITLE
Add acceleration on X201 Arrandale GPU, support for Intel WiFi

### PR DESCRIPTION
**Pull request by jtaczanowski**
Hi! :)

Firstly, I would like to thank you for making this repository available. It allowed me to run MacOS on my old, but still alive and trusty X201.

In this PR I added support for graphic acceleration on integrated Intel HD card. After enabling graphic acceleration this machine runs much much faster and is pretty usable for web browsing, YT watching (thanks to acceleration) or movie watching).
I was inspired by this post [https://www.insanelymac.com/forum/topic/286092-guide-1st-generation-intel-hd-graphics-qeci/?do=findComment&comment=2732732](url)

I hope it will be possible in the future to run BigSur on this machines :) ASentientbot recently made patched kexts for 1st gen Intel HD cards and they are used in opencore legacy patcher for old Mac's
https://github.com/dortania/Apple-Binaries-OCLP/tree/main/Extensions/Graphics-Acceleration/Intel-Gen5-Ironlake
Unfortunately there is no documentation yet, how to inject this patchs to other (non apple) machines.

Except that I added AirportItlwm.kext which enables default Intel WiFi cards. I was surprised how well this driver works currently (I can acheive >100Mb/s on 5GHz WiFi with my Intel 6300)
I left all your settings for replaced WiFi card.

I have only problem with my internal microphone - it is not recognized in MacOS mixer. I can see only line-input. I will looking how to resolve this.

Best regards!

Thinkpad-X201-i7-Catalina-OS-Arrandale-Acceleration

Thinkpad-X201-i7-Catalina-OS-Arrandale-Acceleration2

### CODE REVIEW

**Comment by jamesfawcett** [comment]
This is great news! Thank you I will merge in this morning and credit to you. I use my x201 with Mac OS daily at the moment so this is very welcome! If you open Hackintool does it show metal supported now?

**Comment by jtaczanowski** [comment]
No, this card is not metal capable. Intel HD 4000 and newer are metal capable from what I know. But, the only problem I noticed is with the maps application. This app requires metal card and not working with only QE/CI acceleration enabled.
qe_ci_acceleration

**Comment by jamesfawcett** [comment]
@jtaczanowski thank you for this! Sorry it's taken me a few days to get around to this.

The EFI on my machine has changed a bit since, I swapped the display to a 1440x900 from an X200 and needed to tweak a few settings. 

I've merged in yours and will keep this repo as it is, most people will have the 1280x800 display I think! 

I'm going to combine into my EFI at the weekend :)

At the moment I am currently waiting for XY Tech to finish my hexacore X2100 with 3k display, very excited! For now, I am using this X201 Hackintosh for work! For the maps issue, I disable hardware acceleration in chrome and it works just fine :)

Thanks
James

**Comment by jamesfawcett** [comment]
Hi @jtaczanowski 

I compared my latest EFI on my X201 and it is very different now to this repo, sorry I should have kept it up to date but I have been slowly tweaking things.

My Microphone works, and I have a deviceproperty for audio too. 

`<key>PciRoot(0x0)/Pci(0x1B,0x0)</key>
			<dict>
				<key>layout-id</key>
				<data>DQAAAA==</data>
				<key>model</key>
				<string>5 Series/3400 Series Chipset High Definition Audio</string>
				<key>AAPL,slot-name</key>
				<string>Internal@0,27,0</string>
				<key>device_type</key>
				<string>Audio device</string>
			</dict>`


I copied in your device for the graphics into mine, but unfortunately I don't think it has worked for me. I think it might be because I have change the resolution to 1440x900 resolution for the X200 display I have fitted, which is not a native resolution in mac OS, so I have to enable PatchVBios. If I don't enable PatchVBios, I can only get 1080px. Another issue I have with PatchVBios enabled is the keyboard brightness buttons don't work :(

Screenshot 2021-06-11 at 23 42 40

Screenshot 2021-06-11 at 22 49 51

Here is my latest EFI I've posted it to this branch if you want to take the audio stuff to get your microphone working? 
https://github.com/jamesfawcett/Thinkpad-X201-Hackintosh-Catalina/tree/release/1440x900-display 

It's also using a newer version of clover too.

thanks
James

**Comment by jtaczanowski** [comment]
Hi @jamesfawcett :)
I was able to activate the microphone by changing layout-id for applealc from **3** to **13**. Anyway thanks for making branch with your changes :)

I have read about X2100 from XY Tech, I did not know that there are such cool projects that revive these good old machines. I'm impressed :)

Regarding to the graphics acceleration. Did you install dosdude post install patches? I described this process in README.md
https://github.com/jamesfawcett/Thinkpad-X201-Hackintosh-Catalina#installation-and-enabling-qeci-graphics-acceleration

In your branch I can see that you try to install BigSur on x201.
I was able to run BigSur with opencore. But some things like sound, touchpad are not working. Sometimes my x201 freezing during BigSur boot.
Also graphics acceleration not works. Unfortunately graphic acceleration patching (adding patched kexts, frameworks etc) currently are only available in opencore-legacy-patcher which is designed for old Macs.
In free time I will try to make changes to opencore-legacy-patcher to enable ability of run this patching process not only on Macs but also on other machines like x201

regards,
Jan

**Comment by jtaczanowski** [comment]
Hi @jamesfawcett :)
I managed to get working OpenCore boot loader with BigSur on X201. During the work I discovered a few things which maybe interesting for you.
- until the patching LPC device-id in DSDT power management was not working, CPU clock was stuck on 1,2GHz. With patched DSDT I get appleLPC (native power management) working, now speedstep and turbo boost works properly, CPU clock Is scaling above 3 GHz
- graphics acceleration is working on BigSur after loading patched kexts.

I was realny impressed how fast X201 is running with BigSur after DSDT patch for power management :)
I have created repository with description how to install BigSur with OpenCore.
https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore

Regards,
Jan

**Comment by jamesfawcett** [comment]
Fantastic work @jtaczanowski ! I've been busy getting the X2100 to run Big Sur in the meantime: https://github.com/jamesfawcett/Thinkpad-X2100-51nb-OpenCore-Hackintosh

This weekend, I will convert the X201 to OpenCore! I've been meaning to look into it for quite some time, but I wasn't sure if it would be possible.

I agree about the snappiness, I've used the X201 i7 as a daily in Catalina for some time now. I've upgraded some older Mac's from Catalina to Big Sur and performance increase, so I'm really looking forward to seeing what a difference it will make on the X201! Thank you for your work here, interesting hobby this! :)

**Pull request merged**
